---
title: Mattmetzgar.Github.Io
url: https://mattmetzgar.com/
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Matt Metzgar
description: Exploring Health
email: author@site.com
author: author
lang: en
locale: en_US
logo: assets/img/logo.png
paginate: 10
highlighter: rouge
markdown: kramdown
plugins:
- jekyll-paginate
- jekyll-feed
paginateLabel: page
paginate_path: page/:num
permalink: "/:categories/:year/:month/:day/:title"
baseurl: ''
addthisId: ''
disqusUsername: ''
googleAnalyticsId: UA-82546110-1
bing: ''
yandex: ''
google: ''
sitemap:
  file: "/sitemap.xml"
  exclude:
  - "/404.html"
  include_posts:
  - "/index.html"
  change_frequency_name: daily
  priority_name: '1.00'
